development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: <% ENV["USERNAME"] %>
  password: <% ENV["PASSWORD"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: <% ENV["USERNAME"] %>
  password: <% ENV["PASSWORD"] %>