require './config/initializers/database'

namespace :db do
  desc "Creates the database"
  task :create do
    ActiveRecord::Base.establish_connection(DB_CONFIG.except('database'))
    ActiveRecord::Base.connection.create_database(DB_CONFIG["database"])
    puts "Database created."
    end

  task load_config: :environment do
    ActiveRecord::Base.configurations       = DB_CONFIG
    # ActiveRecord::Migrator.migrations_paths = ActiveRecord::Tasks::DatabaseTasks.migrations_paths
  end
end

