default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
development:
  <<: *default
  database: wan_password_development
test:
  <<: *default
  database: wan_password_test
production:
  <<: *default
  database: wan_password_production
  username: wan_password
  password: <%= ENV['WAN_PASSWORD_DATABASE_PASSWORD'] %>
